name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew :app:synthesizeDistReleaseApksCI :app:extractReleaseNativeDebugMetadata
          ccache -s
          echo "APK_FILE_ARM32=$(find app/build/outputs/ci -name '*arm32.apk')" >> $GITHUB_ENV
          echo "APK_FILE_ARM64=$(find app/build/outputs/ci -name '*arm64.apk')" >> $GITHUB_ENV
          echo "APK_FILE_ARMALL=$(find app/build/outputs/ci -name '*armAll.apk')" >> $GITHUB_ENV
          echo "APK_FILE_UNIVERSAL=$(find app/build/outputs/ci -name '*universal.apk')" >> $GITHUB_ENV

    - name: Upload Artifacts(arm32)
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.APK_FILE_ARM32 }}
        name: Awara-release-${{ github.event.head_commit.id }}-arm32
    - name: Upload Artifacts(arm64)
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.APK_FILE_ARM64 }}
        name: Awara-release-${{ github.event.head_commit.id }}-arm64
    - name: Upload Artifacts(armAll)
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.APK_FILE_ARMALL }}
        name: Awara-release-${{ github.event.head_commit.id }}-armAll
    - name: Upload Artifacts(universal)
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.APK_FILE_UNIVERSAL }}
        name: Awara-release-${{ github.event.head_commit.id }}-universal
      
      
